[custom.all.chem]
type   = "local"
path   = "."
ipkg   = "chem.ipkg"
test   = "test/test.ipkg"

[custom.all.chem-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.chem-doc]
type   = "local"
path   = "doc"
ipkg   = "doc.ipkg"

[custom.all.chem-app]
type   = "local"
path   = "app"
ipkg   = "app.ipkg"

[custom.all.chem-profile]
type   = "local"
path   = "profile"
ipkg   = "profile.ipkg"

[custom.all.refined]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-refined"
commit = "latest:main"
ipkg   = "refined.ipkg"

[custom.all.algebra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-algebra"
commit = "latest:main"
ipkg   = "algebra.ipkg"

[custom.all.graph]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-graph"
commit = "latest:algebra"
ipkg   = "graph.ipkg"

[custom.all.parser]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:main"
ipkg   = "parser.ipkg"
