[custom.all.chem]
type   = "local"
path   = "."
ipkg   = "chem.ipkg"
test   = "test/test.ipkg"

[custom.all.chem-generators]
type   = "local"
path   = "chem-generators"
ipkg   = "chem-generators.ipkg"

[custom.all.chem-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.chem-doc]
type   = "local"
path   = "doc"
ipkg   = "doc.ipkg"

[custom.all.chem-app]
type   = "local"
path   = "app"
ipkg   = "app.ipkg"

[custom.all.chem-data]
type   = "local"
path   = "chem-data"
ipkg   = "chem-data.ipkg"

[custom.all.chem-profile]
type   = "local"
path   = "profile"
ipkg   = "profile.ipkg"

# [custom.all.quantifiers-extra]
# type   = "git"
# url    = "https://github.com/stefan-hoeck/idris2-quantifiers-extra"
# commit = "latest:main"
# ipkg   = "quantifiers-extra.ipkg"

[custom.all.array]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"

[custom.all.indexed-graph]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-indexed-graph"
commit = "latest:main"
ipkg   = "indexed-graph.ipkg"
